CREATE SCHEMA IF NOT EXISTS bean;

CREATE TABLE IF NOT EXISTS bean.tbl_employee (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  age INT NOT NULL,
  location VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  department VARCHAR(45) NOT NULL,
  PRIMARY KEY (id));
